### ISSUE TITLE
pip install fails on logging module - it is not needed for python 3

### ISSUE THREAD

**Issue by kvikeg** [rahulnyk/knowledge_graph_maker#3]
Hi, 

I get the following error on Python 3.12.3 in WSL2 Ubuntu:
Actually logging module is part of standard libraries in Python 3, which is required anyway, so it does not need to be installed with a package.

Collecting logging<0.5.0.0,>=0.4.9.6 (from knowledge_graph_maker)
  Using cached logging-0.4.9.6.tar.gz (96 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/philip/.local/lib/python3.12/site-packages/setuptools/__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/philip/.local/lib/python3.12/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/philip/.local/lib/python3.12/site-packages/_distutils_hack/__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "/home/philip/.local/lib/python3.12/site-packages/_distutils_hack/__init__.py", line 56, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/philip/.local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 13, in <module>
          from .cmd import Command
        File "/home/philip/.local/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 7, in <module>
          import logging
        File "/tmp/pip-install-ymd6i_0a/logging_28af228c84ed4b53973b883bb3270d57/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rahulnyk** [comment]
I will try to amend this but it may take some time. I'm in a time crunch right now. 
But if you want to take a dig at it, please raise a PR
Thanks
